# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

stages:
  - build
#  - publish

services:
  - docker:dind
before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY

build:
  stage: build
  tags:
    - dind
    - docker
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t registry.nocsi.org/archlinux-aur:latest -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
    - docker push registry.nocsi.org/archlinux-aur:latest
    - docker run -d --rm -e EMAIL_TO="build@nocsi.com" -e EMAIL_PW="CXX?wCCHMYVeRfG0AsCH_T%nr" registry.nocsi.org/build-docker-report "$CI_BUILD_REF" "$CI_SERVER_TLS_CA_FILE"
  only:
    - master

#publish:
#  stage: publish
#  tags:
#  - docker
#  - dind
#  script:
#  - docker login -u nocsi -e l@nocsi.com -p rTPwQ025pM!0::Ix7fpoI)%X+zV
#  - docker build --pull -t nocsigroup/archlinux-aur .
#  - docker push nocsigroup/archlinux-aur:latest
#  only:
#    - master
